version: 2.1

# jobs are like stages in jenkins
# jobs is like a package of core functions
jobs:
  one:
    docker:
      - image: bash
    steps:
      - run:
          command: 
            - pwd
            - ls -la
            - echo "one"
  two:
    docker:
      - image: bash
    steps:
      - run:
          command: echo "two---two"


# workflows are like pipeline in jenkins
# workflows are like controllers or handlers using packaged core functions
# workflow is were orehestation is done.
workflows:
  version: 2.1
  my_workflow: # parallel workflow
    jobs:
      - one
      - two
      - three:
          requires:
            - one
  another_workflow: # sequenced workflow
    jobs:
      - one
      - two:
          requires:
            - one



