version: 2.1

# jobs are like stages in jenkins
# jobs is like a package of core functions
jobs:
  one:
    docker:
      - image: bash
    steps:
      - run:
          command: pwd
      - run:
          command: ls -la
      - run:
         command: mkdir -p a/b/c
  two:
    docker:
      - image: bash
    steps:
      - run:
          command: ls -la
      - run:
          command: echo "two---two"


# workflows are like pipeline in jenkins
# workflows are like controllers or handlers using packaged core functions
# workflow is were orehestation is done.
workflows:
  version: 2.1
  my_workflow: # parallel workflow
    jobs:
      - one
      - two
      # placeholder job or stub job
      - three:
          type: approval
          requires:
            - one
  another_workflow: # sequenced workflow
    jobs:
      - one
      - two:
          requires:
            - one



